server:
  port: 8080
  
spring.application.name: Crypto Cipher

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    
app:
  jasypt:
    secretKey: xit5811807!@
    alg: PBEWithMD5AndDES
    type: base64
  crypto:
    alg: ARIA
    mode: GCM
    # //FIXME: 16, 24, 32bytes 길이의 key(Base64로 encoding된 값)를 사용
    key: ENC(9prHZEclHqSGpjq2tYH2NW5uuhqByDTFXkCWvKgO/VJ1szNi329KN+fepqmLlLS3ePrgaA8dnPs=)
    # //FIXME: 16bytes(Base64로 encoding된 값) - CCM 7~13bytes 길이의 값이다 (12bytes 길이 권장)
    iv: ENC(MNHa5S4pPFPFkj69+f0Ezw8Ni7K47z72cILEOq/6A/RsEYr+3PgIYA==) 
